### ISSUE TITLE
Transaction simulation failed

### ISSUE THREAD

**Issue by qingfeng520** [mmc-98/solxen-tx#3]
2024-05-08T22:15:19.944+08:00    error  err: sig: (*jsonrpc.RPCError)(0xc00034c390)({
 Code: (int) -32002,
 Message: (string) (len=97) "Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.",
 Data: (map[string]interface {}) (len=6) {
  (string) (len=8) "accounts": (interface {}) <nil>,
  (string) (len=3) "err": (string) (len=15) "AccountNotFound",
  (string) (len=17) "innerInstructions": (interface {}) <nil>,
  (string) (len=4) "logs": ([]interface {}) {
  },
  (string) (len=10) "returnData": (interface {}) <nil>,
  (string) (len=13) "unitsConsumed": (json.Number) (len=1) "0"
 }
})
        caller=logic/solxen.go:176

**Comment by mmc-98** [comment]
Try using the latest version

**Comment by mmc-98** [comment]
Try using the latest version
